artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/da417b9ed698407ab675f4ab2967cde0/artifacts
end_time: 1628423766398
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: da417b9ed698407ab675f4ab2967cde0
run_uuid: da417b9ed698407ab675f4ab2967cde0
source_name: ''
source_type: 4
source_version: ''
start_time: 1628423751894
status: 4
tags: []
user_id: reigHns
