artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/52faedfff0904afa8538eb369ad0ef6c/artifacts
end_time: 1628424055052
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 52faedfff0904afa8538eb369ad0ef6c
run_uuid: 52faedfff0904afa8538eb369ad0ef6c
source_name: ''
source_type: 4
source_version: ''
start_time: 1628424030364
status: 4
tags: []
user_id: reigHns
