artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/39aab3767a2844e4808cd1e02c55145c/artifacts
end_time: 1628408931144
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 39aab3767a2844e4808cd1e02c55145c
run_uuid: 39aab3767a2844e4808cd1e02c55145c
source_name: ''
source_type: 4
source_version: ''
start_time: 1628408931073
status: 4
tags: []
user_id: reigHns
