artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/e53617a9c4344aaab8b0b4631aa10075/artifacts
end_time: 1628409000723
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e53617a9c4344aaab8b0b4631aa10075
run_uuid: e53617a9c4344aaab8b0b4631aa10075
source_name: ''
source_type: 4
source_version: ''
start_time: 1628408998879
status: 4
tags: []
user_id: reigHns
