artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/fb3d3dcae686423a96e4ce1a6872132b/artifacts
end_time: 1628423994925
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fb3d3dcae686423a96e4ce1a6872132b
run_uuid: fb3d3dcae686423a96e4ce1a6872132b
source_name: ''
source_type: 4
source_version: ''
start_time: 1628423980236
status: 4
tags: []
user_id: reigHns
