artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/a7184781450746748d0cc6ffbae3e909/artifacts
end_time: 1628408976548
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a7184781450746748d0cc6ffbae3e909
run_uuid: a7184781450746748d0cc6ffbae3e909
source_name: ''
source_type: 4
source_version: ''
start_time: 1628408976461
status: 4
tags: []
user_id: reigHns
