artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/4497b57c955e44b984904fa5ae2e45b3/artifacts
end_time: 1628409035075
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 4497b57c955e44b984904fa5ae2e45b3
run_uuid: 4497b57c955e44b984904fa5ae2e45b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1628409030931
status: 4
tags: []
user_id: reigHns
