artifact_uri: file://C:/Users/reigHns/mnist/stores/model/0/e307aa1644cc4368b099fb29967f48aa/artifacts
end_time: 1628409059745
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e307aa1644cc4368b099fb29967f48aa
run_uuid: e307aa1644cc4368b099fb29967f48aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1628409056479
status: 4
tags: []
user_id: reigHns
